- bl.c
used to get the chip version, so we can tell rev3 silicon from rev2
> added GET_CHIP bootloader command

- bl.c
Apparently some commands are not waiting for "PROTO_EOC".
Some places use up "cin_wait (1000)" and other "cin_wait (100)" could standardize a time and thus "cin_wait (WAIT_TIME)".
> Some commands do not wait for EOC.

- Makefile
- cdcacm.c
- hw_config.h
- main_f4.c
See https://github.com/PX4/Firmware/pull/5360 for corresponding firmware and usage.
> Crazyflie 2

- hw_config.h
See https://github.com/PX4/Firmware/pull/5520
> CF2: Unique board type

- Makefile
- Makefile.f7
- hw_config.h
- main_f7.c
- stm32f7.ld
@LorenzMeier - This has a [sister](https://github.com/PX4/Firmware/pull/6046/commits/edcb0f2bc76ef1686be15e2c408cc06a0dead05b) that is needed.
> Added px4fmu-v5 STM32F7 based bootloader

- hw_config.h
So that the PX4 Firmware uploader script finds it on linux
> OmnibusF4SD: change USBDEVICESTRING to "PX4 OmnibusF4SD"

- Makefile
- hw_config.h
- main_f7.c
PR on top of https://github.com/PX4/Bootloader/pull/107.
> AV-X bootloader support

- main_f4.c
@LorenzMeier 
For https://github.com/PX4/Firmware/pull/10426#issuecomment-421107645
> main_f4:check sliicon for TARGET_HW_PX4_FMU_V3

- .travis.yml
- Makefile
- bl.c
- hw_config.h
- main_f4.c
- main_f7.c
- main_k66.c
Added the format check form https://github.com/PX4/Firmware
Added the entry in the travis file for the format.
> Enforce style checking

- bl.c
> bl:Reserve Protocol codes 0x15, 0x36-0x39

- board_types.txt
Added New Board ID for V5X, V6 and V6X
> Added New Board ID for V5X, V6 and V6X

- .travis.yml
This is needed to keep code size under control for the newest software versions.
> Update Travis to arm-none-eabi-gcc v7

- Makefile
- Tools/docker_run.sh
- bl.c
- board_types.txt
- hw_config.h
- main_f4.c
UVify Core fmu board bootloader support is implemented.
VID: 0x1008, PID:0x0001.
> UVify Core fmu board bootloader support

- Makefile
- hw_config.h
> Added FMUv5X

- Jenkinsfile
- Makefile
- hw_config.h
This adds revision E of the fmuK66 Hw.
> Add NXP fmuk66e

- main_f4.c
- main_f7.c
This is a continuation of https://github.com/PX4/PX4-Bootloader/pull/186 It is squashed and the title updated
Thank you @Zoey-SunflowerLabs
> Ensure RTC is enabled and LSE is not affected

- Jenkinsfile
- Makefile
- board_types.txt
- hw_config.h
Added support of smartap airlink bootloader.
> Support smartap airlink bootloader

- README.md
- bl.c
- hw_config.h
- stm32f1.ld
- stm32f3.ld
- stm32f4.ld
- stm32f7.ld
This includes the fixes to the linker scripts that @davids5  suggested as well as some flash saving to make IO fit.
Best reviewed commit by commit.
> Fix linker script and get IO to fit flash

- .github/workflows/main.yaml
- README.md
This fixes the CI badge, as well as some small fixes that I came across, and fixes CI to run for the master branch (not main).
> Small readme fixes, and GitHub action fix

- board_types.txt
See https://github.com/PX4/PX4-Bootloader/issues/206
> Reserve 66

- hw_config.h
> Fix SmartAP USB Product ID

- hw_config.h
- main_f7.c
> Mantis: boot camera and allow longer delay

- crypto_hal/image_toc.c
Port change from here: https://github.com/PX4/PX4-Autopilot/pull/20222
> image_toc.c: Check that the ToC actually lies within the first entry

- Jenkinsfile
- Makefile
- board_types.txt
- hw_config.h
Hi,
We developed a Flight Controller.
I would like to add Bootloader Code of our K1/R1 Flight Controller to the official PX4-Bootloader.
Thanks.
> Add THEPeach K1/R1

- board_types.txt
Adds ID for Tropic VMU board
https://github.com/NXPHoverGames/TropicCommunityVMU
> Reserve Tropic

- board_types.txt
This ID is already in use, we forgot to submit a reservation to this repo beforehand!
https://github.com/PX4/PX4-Autopilot/blob/main/boards/ark/fpv/nuttx-config/nsh/defconfig#L79
https://github.com/PX4/PX4-Autopilot/blob/main/boards/ark/fpv/firmware.prototype#L2
Working on Ardupilot PR here and they'd like to see this reserved here first
https://github.com/ArduPilot/ardupilot/pull/28603/files#r1906197628
> reserve ARK FPV

- README.md
* updates github actions badge
* updates links to forums and discord
> readme: update readme links

- board_types.txt
reserved for Lumenier NDAA F7 flight controller
> board_types: reserve lumenier ndaa f7

- board_types.txt
leftover issue from previous merge
cc @julianoes seems like we added a conflict in the previous merges
> board_types: resolve conflicts

- board_types.txt
Renamed Tropic Community (36) to distingush between MR-TROPIC (37)
> Reserve MR-TROPIC
