bl.c, bl.h, cdcacm.c, hw_config.h, main_f1.c, main_f4.c, uart.h, usart.c
@davids5: I have updated my pull request for parallel USB and USART bootloading to be in line with the changes that you made to have a single hw_config file.
I don't have a Pixhawk on hand to test the USART bootloading on that board, so please bear this in mind before merging it in - I have put the USART port on USART2 for the Pixhawk. I have tested the USB and USART for the Px4FMU, though.
Here is a quick overview of the changes:
* In the bl.c file I have now changed the bootloader function to accept both the timeout and the bootloader type (either USART or USB) . This option will then set the appropriate functions cin_usb or cin_usart and cout_usb or cout_usart to the function pointers cin and cout. 
* I have changed the #ifdef INTERFACE_USART to be #if INTERFACE_USART. I don't know …
=> USART and USB Bootloader ability added.

main_f1.c
Previously the SMT32F1 devices just returned 0 when queried for their serial numbers. This might be useful for the MAVStation board. It will then return the serial number to the px_uploader like what is done with PX4FMU and the PIXHAWK. This might also be useful for the PXIO uploader, if it needs to get the serial from a chip that has bad firmware.
=> Adds readout of the chip's serial number in the STM32F1 bootloaders

hw_config.h
Disables bootloader force through the PPM-in pin. Some receivers pull
their PPM output low when the transmitter is off, resulting in a stuck
bootup, so this feature is best disabled.
See issue:  https://github.com/PX4/Bootloader/issues/50
--ET
=> Disabled BOARD_FORCE_BL_PIN for V1

Makefile, hw_config.h
Bootloader supports MindPXv2 from airmind.
We change the usb product id to 0x0030.  If it's not accept, please help re-assign an ID.
Thanks.
=> Bootloader supports MindPXv2 from airmind.

Makefile, hw_config.h
@LorenzMeier 
Added the AUAV X2.1 Bootloader and a note about using the
required "PX4 BL " in the USBDEVICESTRING.
This requierment is to simplify the ripple effect on the tools,
we will be using /dev/serial/by-id/_PX4_ to locate PX4 devices.
Therefore moving forward all Bootloaders must contain the prefix
"PX4 BL " in the USBDEVICESTRING
=> Added AUAV X2.1 Bootloader

Makefile, Makefile.f3, cdcacm.c, hw_config.h, main_f1.c, main_f3.c, main_f4.c, stm32f3.ld, stm32f3x.cfg, usart.c
This adds PX4 FMU V4 PRO and PX4 IO V3 bootloaders. 
Currently I am waiting on libopencm3 ( @karlp ) to merge PX4 contributions to their upstream for the USB and RCC of the STM32F469 and STM32F446.
- Support for the PLL was incorporated upstream   
- A work around has been added fir the USB driver issues,
- [ x] Validate RTC wait for BL 
- tested with a forced load of V2 FW
=> STM32F467 enabled bootloader

cdcacm.c, main_f4.c
@LorenzMeier 
Adresses https://github.com/PX4/Bootloader/issues/30
I can go either way on 066213f - The data sheet seems to suggest that PA9 has a 1.1K Pull down. The question is whether it is enabled when the pin is left floating. I think we should discuss this.
The second commit seems like it makes good sense.
=> Master vbus conf 

hw_config.h, main_f4.c, main_f7.c
This adds a build time option the ability to disable Serial Break detection from entering and staying in bootloader.
=> Build Time  ability to disable Serial Break detection from entering BL

bl.c
This fixes the issue where usb_cout got stuck because it was not
connected when trying to nack something that arrived on USART.
This is a better fix than #70 according to @davids5.
=> A Bootloader should never speak until spoken to

hw_config.h, usart.c
The default is to used the USART_BAUDRATE of 115200 but  a board can override it by setting OVERRIDE_USART_BAUDRATE
=> Moved buad rate setting to hw_config and allow override

main_f4.c
The USART break polling was hardcoded for 115200 baud. This makes the poll rate tied to the baudrate.
=> Detect USART break based on baud rate

hw_config.h
Remove the bootloader # of Sectors from total Sectors as the EA is calulated as APP_LOAD_ADDRESS + (sector * FLASH_SECTOR_SIZE)
and tested as sector < BOARD_FLASH_SECTORS.
Therefore sector 0 is the first sector of the Application and FLASH_SECTOR_SIZE = the last sector sector number of the  application + 1
=> TARGET_HW_PX4_PIO_V3 (inactive) wrong sector count

.gitignore, Makefile, Makefile.f1, Makefile.f3, Makefile.f4, Makefile.f7, rules.mk
This resolves the issue (#77) that if any of the header header files were
modified, make would not recompile to include the changes in the header
files the unless clean was run before recompiling.
.o object files and .d dependency files are created for each of the c files. The only proviso is that if a header file is renamed, the dependency will be "lost" so you will have to `make clean` before recompiling.
=> Adds auto dependencies for make

Makefile, rules.mk
All individual board build directories are now generated in a consolidating
'build' directory (Bootloader/build).
This helps remove the clutter of having multiple board build directories
generated in the src/ directory.
This is along the same lines as what has been done in the PX4/Firmware repo, when all builds are now compiled in a Firmware/build/<specific board> directory.
=> Consolidates all build directories into a single parent 'build' directory

Makefile, hw_config.h, main_f4.c
bootloader support for the [omnibusf4sd](https://github.com/betaflight/betaflight/wiki/Board---OMNIBUSF4)
this is tested and working with my 1.7.4 branch: https://github.com/nathantsoi/Firmware/tree/omnibusf4sd-1.7.4
full details and status of the port here, any guidance would be much appreciated: http://discuss.px4.io/t/omnibusf4sd-target-support-request-for-development-guidance/6373
=> initial omnibusf4sd target support

Makefile, Makefile.f3, Makefile.f7, hw_config.h, main_f3.c, main_f4.c, main_f7.c, rules.mk, stm32/cdcacm.c, stm32/usart.c
@LorenzMeier @DanielePettenuzzo 
This PR updates the libopencm3 to upstream master for more legit STM32 F7 support.
The uart is now supported, as is the real RCC. USB is still a hack using the F4 driver.
**This need complete testing on ALL hw platforms before it is merged. At lease on F1, F3, and F4 platform should be tested.**
I have tested both serial and USB on FMUv5.
I was getting timeout on the CRC calculation returning results.
```
chip: 10016451
family: STM32F7[6|7]x
revision: Z
flash 2064384
Erase  : [====================] 100.0%
Program: [====================] 100.0%
Verify : [                    ] 1.0%
ERROR: timeout waiting for data (4 bytes)
```
This fixes it. YMMV
```
diff --git a/Tools/px_uploader.py b/Tools/px_uploader.py
index a0cec1f..2ef7959 100755
--- …
```
=> Update libopencm3 to upstream master for more legit STM32 F7 support

Makefile, bl.c, board_types.txt, hw_config.h
this is needed as the ArduPilot project has another implementation of
this bootloader protocol, and thus another source of BOARD_TYPE
values. To maintain a common list without collisions this file can be
used
=> added board_types.txt to hold all BOARD_TYPE values

hw_config.h, main_f3.c, main_f4.c, main_f7.c
Until now both UART pins needed to be defined on the same port of the microcontroller.
This PR remove this limitation. 
It is backward compatible with the previous definition.
Modified for stm32f3, stm32f4 and stm32f7.
=> UART pins can be defined on different ports

hw_config.h
It removes the SD card dependency as some omnibus boards do not have one.
This is a **breaking** change and requires the Firmware to update as well.
The alternative would be to add a separate bootloader target, but going forward I think this is simpler and removes the SD card dependency even on boards that have one.
I only used 1 sector of 16KB, as I think it will be enough (a typical params file is around 4KB). We have the option of adding another 16KB sector if needed (the Intel Aero uses 2).
=> omnibusf4sd: reserve the first sector of the firmware for flash-based params storage

rules.mk
This is useful for flashing boards like the Omnibus via Betaflight
Configurator that come preflashed with Betaflight.
It is built with the default target, we can make a separate target if we don't want that.
@dagar do we build & push the binaries somewhere already?
=> make: add .hex binary output to build target

board_types.txt
one is the Pixhawk4Pro from Holybro, the other the CubeOrange from Hex
=> added IDs for two H743 based boards

.gitignore, Makefile, bl.c, board_types.txt, hw_config.h, main_f4.c, main_f7.c, stm32/cdcacm.c
This adds support for the Holybro KakuteF7 board.
There are 2*32KB sectors reserved for parameters - I used 2 to stay compatible with ArduPilot's configuration.
Looking through the datasheet, only PA9 can be used for VBUS sensing. If another pin is assigned (which is the case for KakuteF7), we can still use it for fast-boot detection. I did some changes to account for that in general. In case of disabled VBUS sensing, we need to force valid B-peripheral session, otherwise the USB device will not show up.
I think we could generally just disable VBUS sensing (but still use the pin for fast-boot detection). On the Firmware/NuttX we have it disabled as well.
The only other boards affected by this are OmnibusF4SD and Crazyflie. I cross-tested on Omnibus.
=> KakuteF7 board support

bl.c, hw_config.h
Added state protection and sanity checking to reduce the probability of random data 
1) committing a bad image (BOOT '0 ') 
2) hard faulting 
N.B. The PX4IO code space was too small to do all the state checking
=> Increase reliability

board_types.txt
The reserved range is to prevent us ending up with conflicting IDs if new additions to this file are slow to merge. The existing IDs for ArduPIlot that are in this file will be kept (needed for compatibility) but we will allocate new IDs in the range 1000 to 1999
=> added new ardupilot IDs and reserve range for ardupilot

bl.c, bl.h, cdcacm.h, main_f3.c, main_f4.c, main_f7.c, main_k66.c, stm32/cdcacm.c
@dagar - this is a step (albeit it limited by the PX4IO) in being able to compile the bootloader in a non libcm3 build.
If you are OK with the changes. I think we want to have it tested on F1, F4, F7 and K66 before merging.
=> bl Remove compile time dependency on libcm3

Jenkinsfile, Makefile, board_types.txt, hw_config.h
Board ID: 41775 (0xA32F)
VID: 0x0483 (STMicroelectronics, approved by vendor)
PID: 0xa32f
USBDeviceString: "PX4 BL ModalAI FCv1"
Supports serial DFU over USART3 (debug header on hardware)
=> Add support for ModalAI FC1 target

board_types.txt
Fixes ID of -AP_HW_MRO_CONTROL_ZERO_PR to remove conflict and adds two new boards
=> Added ArduPilot IDs

board_types.txt
USB Vendor ID: 0x3162
USB Product ID: 0x004E
USB Device String: PIX32-V5
USB MFG String: Holybro
=> Reserve Holybro PIX32-V5

board_types.txt
Document the existing ID's of
TARGET_HW_FMUK66_V3 and TARGET_HW_AV_X_V1
Assign:
TARGET_HW_FMUK66_E
TARGET_HW_FMURT1062-V1
=> Document assigned ID

bl.c
It appear that QGC is now resyncing between operation.
This was causing the bl_state to be reset to STATE_PROTO_GET_SYNC
and loosing the state of (STATE_PROTO_GET_SYNC|STATE_PROTO_GET_DEVICE)
=> PX4 Bootloader:Track QGC change in sequencing

bl.c
The PX4IO which is limitted on flash, did not intializing the
PROTO_GET_SYNC state as SET_BL_STATE was a no-op.
Prior to b2acae83 the value was assinged to the state with an
assigment. b2acae83 replaced the = with the macro.  The fix is
declearing SET_BL_FIRST_STATE as the |= and using it in
PROTO_GET_SYNC.
=> px4io_bl:Fix breakage from b2acae83.

board_types.txt
Additions to align with https://github.com/ArduPilot/ardupilot/blob/master/Tools/AP_Bootloader/board_types.txt
I think most of the "Reserved" lines are now implemented so could be removed, but I've not done that here.
Also, there is some duplication creeping in that might be worth discussing.
=> board_types.txt: sync to ArduPilot board_types.txt

stm32/usart.c
This was found on the Mantis where the following happened:
1. Boot command is sent to a bootloader without a firmware flashed.
2. After boot command, there is a 100 ms delay.
3. During that time, more data is sent to the bootloader causing an overrun.
4. Without overrun disabled, this will set the ORE flag, and reads will fail because RXNE is not set.
By disabling the overrun flag we can recover from an overrun.
=> stm32: disable overrun

board_types.txt
This adds two device_id to cover the KakuteH7v2 and the KakuteH7mini. Both warrant a separate ID and build target because they come with NAND flash rather than an SD card.
@vincentpoont2 can you also confirm that this is ok?
=> board_types.txt: add KakuteH7v2 and KakuteH7mini

board_types.txt
This is according to https://github.com/PX4/PX4-Autopilot/pull/20304.
FYI @bugobliterator
=> board_types: add CubeOrange+

board_types.txt
This PR aligns boards.txt between ArduPilot and PX4. A matching PR will be submitted to the other repo, , so that the contexts of boards.txt matches exactly (at the time of drafting).
=> Bootloader: sync ArduPilot and PX4 boards.txt

board_types.txt
obviously boards are being allocated outside the range mentioned in this comment.  Attempt to avoid conflicts in future by updating said comment
=> board_types.txt: update reserved range comment for ArduPilot

.github/workflows/main.yaml, board_types.txt
The board ID 1054 is not used anymore for the KakuteH7 mini, instead it should all be 1058.
FYI @vincentpoont2
=> Add note about duplicate KakuteH7 mini entry

board_types.txt
As already used by ArduPilot.
With: https://github.com/PX4/PX4-Autopilot/pull/24669
Also see: https://github.com/ArduPilot/ardupilot/blob/fccd9600d8e5680f166e1ec1a1bf834b88fe563c/Tools/AP_Bootloader/board_types.txt#L227
=> board_types: add Holybro KakuteH7-Wing

board_types.txt
Dear developer, I would like to apply for a board ID for our flight control product. Please review it.
=> Apply for a board ID for amovlab icf6

.github/workflows/check_board_conflicts.yaml, .github/workflows/main.yaml, Tools/check_board_types_conflicts.txt, board_types.txt
* adds a tool that checks for conflicts in the second column
* allows for a special use case of conflicts
* runs in CI
=> board_types: tests for conflicts in CI

board_types.txt
=> board_types.txt: move 6C ID from reserved to TARGET_HW_PX4_FMU_V6C

board_types.txt
Hi, Updating this list based on a recent PR merge to allocate board id for YARIV6X https://github.com/ArduPilot/ardupilot/pull/30910
=> board_types.txt: Add YARIV6X
